let str='Reran among one more opposite indubitably gent immaturely like some mistakenly scurrilously despite hence cobra unstinting goodness wobbled irrespective far near dismissively whale far sloth one that into yikes packed wasp hound petted this orca the sociably far pugnacious honestly misheard minimal invoked thanks far because meant a indefatigably this drank blankly squirrel far quit minutely some minimally inside lubber ouch in alongside since some with wherever much histrionic savagely due.One moth wow some crept a caterpillar foul goodness improper far woolly because much dalmatian ignorant enchantingly spread indiscreet wherever despicably daintily capable far far darn goodness greedy crud overheard that the that before more more oh less cumulative wherever a some reran excepting adjusted because exuberant met about blushed far about bid hare crud well on thus loyal well in luridly excluding firefly yikes much meadowlark gosh far jeez gravely clinic sniffled together less desperately.Crab spent rabbit spilled more oh jeez strived grimily raunchily far spiteful conscientious rethought garishly a oh crud much eloquent more barring ostrich rhinoceros towards amongst reset yet hey yet the over beyond more intolerable while but nutria wow spontaneous much archly deliberate because while gorilla much doubtful crud elegant licentiously a apart wherever cooperatively wittily opposite far ouch on outgrew crud the rose threw caterpillar house a overate before barring porpoise but cannily purred antelope and read darn clung wow less gratefully the that crud far insect.Wayward much therefore more submissive toucan barring laudable much idiotically or rolled much a one pragmatic much hyena instead forward oh feeling hideous some in moaned as guffawed bowed fraudulent nonsensical regarding ouch then squid dear misled while ignorant raucous grasshopper mechanic that ouch following goodness before jeez goldfish after this effusive earthworm judiciously on that prior meadowlark until greyhound jellyfish alas outside like stupidly limpet yikes that including that so this.Gosh hey iguanodon dove wolf yikes because demure gosh shuffled regarding clever pouted goodness affirmative brokenly wolverine and more oblique much but cunning actively rid hamster and cracked at blinked rid crud oriole far one miser wolf far delinquent a and yikes far far composite hardily capybara overthrew this cowered alas via before a hello kept cuckoo bashfully heron well secret seagull aside husky spread frugally less some acceptably and monogamous far without buoyantly jeepers jeepers opaque much much busily because waved while a wryly.';
let count=0;
let array = str.split(' ');
console.log(array);
let string=array.filter(x =>x == "the");
console.log(string);
let theString=string.reduce((acc,c) => 
                            {
 return acc+1;
}, 0);

console.log(theString);
